import type { Metadata } from "next";
import {GeistSans} from "geist/font/sans";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "EPIMONI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
      <main className="flex w-full h-screen bg-accent-foreground">
          {children}
      </main>
      </body>
    </html>
  );
}
